name: dev auto ci process script
on: push
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: excuting remote ssh commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_S_IP_TEST }}
        username: ${{ secrets.SERVER_S_USER }}
        password: ${{ secrets.SERVER_S_PASSWORD }}
        port: ${{ secrets.SERVER_SSH_PORT }}
